---
title: "Linear Algebra, Mike X Cohen (Udemy)"
author: "Antony H. Clark"
date: '2022-04-06'
number_sections: true
output: 
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 3
  pdf_document:
    toc: yes

---

```{r setup, include=FALSE}

library(plotly)
library(plot3D)
library(dplyr)
library(tidyr)

# ********************************************************************************
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE
  )

source("functions/functions.R") # various helper functions



```

## Intro

This R Markdown document is a workbook following the Udemy **Linear Algebra** course by Mike X. Cohen:
 <https://www.udemy.com/course/linear-algebra-theory-and-implementation/>.

## Some LaTeX

$$ \hat{a}=\frac{\vec{a}}{\left | \vec{a} \right |} $$

## Plot a plane

```{r plotPlane-plot3D}
# ********************************************************************************
x <- 0:4
y <- 0:4
z <- outer(x,y,function(x,y) x+y)
#plot3D::persp3D(x,y,z,colvar = NULL,theta = -45,phi = 0)
plot3D::persp3D(x,y,z,colvar = NULL,theta = -20,phi = 0)
plot3D::arrows3D(0,0,0,1,1,2,add = T,col = "red")

```


## Output format

`r knitr::is_latex_output()`

## Some python

```{python python-test}
# https://matplotlib.org/2.0.2/users/pyplot_tutorial.html
import matplotlib.pyplot as plt
plt.plot([1,2,3,4])
plt.ylabel('some numbers')
plt.show()


```

## Some Udemy Python

```{python}
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# create vectors
v1  = [ -3,  2, 5 ]
v2  = [  4, -3, 0 ]

# Python's cross-product function
v3a = np.cross( v1,v2 )

# "manual" method
v3b = [ [v1[1]*v2[2] - v1[2]*v2[1]],
        [v1[2]*v2[0] - v1[0]*v2[2]],
        [v1[0]*v2[1] - v1[1]*v2[0]] ]

print(v3a,v3b)


fig = plt.figure()
ax = fig.gca(projection='3d')

# draw plane defined by span of v1 and v2
xx, yy = np.meshgrid(np.linspace(-10,10,10),np.linspace(-10,10,10))
z1 = (-v3a[0]*xx - v3a[1]*yy)/v3a[2]
ax.plot_surface(xx,yy,z1,alpha=.2)

## plot the two vectors
ax.plot([0, v1[0]],[0, v1[1]],[0, v1[2]],'k')
ax.plot([0, v2[0]],[0, v2[1]],[0, v2[2]],'k')
ax.plot([0, v3a[0]],[0, v3a[1]],[0, v3a[2]],'r')


ax.view_init(azim=150,elev=45)
plt.show()


```

```{r reticulate}

np <- reticulate::import("numpy")
np$cross(c(1,2,3),c(2,3,7))
np$rad2deg(pi)
```










